### PR TITLE
Update for switchy 2.0.0

### PR DESCRIPTION
**Pull request by sisby-folk**
Yeah we broke the data-driven module format in 2.0.0, so here's an update for that.

I've put a big bold warning on the switchy 2.0.0 changelog that booting 2.0 and rpgstats without this update will cause data loss - thankfully on this side a qmj bump handles it no problem.

### CODE REVIEW

**Comment by SilverAndro** [comment]
for clarification did the NBT format also change or just the JSON declaration side?

**Comment by sisby-folk** [comment]
Mayyyybe double check (it's been a month) but I very deliberately did not
touch save formats so I don't think so.

**Comment by SilverAndro** [comment]
alright interesting

i recently learned about resource loader a bit so im wondering if its possible to conditionally load a different definition json based in which switchy version is present

**Comment by SilverAndro** [comment]
Hm are you sure this is the right way to declare a module? I cant seem to get it to load locally

**Pull request merged**
