### PR TITLE
added lang/pt-br

### PR DESCRIPTION
**Pull request by FITFC**

### CODE REVIEW

**Comment by SilverAndro** [comment]
I appreciate this, but most of the work is actually in https://github.com/SilverAndro/RPGStats/tree/master/src/main/resources/data/rpgstats/lang so that translations work server side, so you need to translate that as well, sorry 😅

**Comment by FITFC** [comment]
> I appreciate this, but most of the work is actually in https://github.com/SilverAndro/RPGStats/tree/master/src/main/resources/data/rpgstats/lang so that translations work server side, so you need to translate that as well, sorry 😅

Added missing part of translation

**Comment by SilverAndro** [comment]
Awesome, thanks much! Ill merge this and itll be in the next release

**Comment by SilverAndro** [comment]
Finally got around to pushing a release, this is bundled with 5.0.8, again thanks much!

**Pull request merged**
